# Generated by Django 4.2.8 on 2024-02-21 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0001_initial'),
        ('faculty_fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Faculty Name')),
                ('acceptance', models.PositiveSmallIntegerField(verbose_name='Acceptance')),
                ('grant', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Grant score')),
                ('contract', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Contract score')),
                ('education_form', models.ManyToManyField(to='faculty_fields.education_form', verbose_name='Education form')),
                ('first_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty_fields.subject', verbose_name='First subject')),
                ('second_subject', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='second_subject', to='faculty_fields.subject', verbose_name='Second subject')),
                ('tuition_language', models.ManyToManyField(to='faculty_fields.tuition_language', verbose_name='Tuition language')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.university', verbose_name='University')),
            ],
            options={
                'verbose_name': 'Faculty',
                'verbose_name_plural': 'Faculties',
            },
        ),
    ]
