# Generated by Django 4.2.8 on 2024-02-21 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_fields', '0001_initial'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='first_subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_subject', to='faculty_fields.subject', verbose_name='First subject'),
        ),
    ]
